import { Listing } from '@/types';

export const FALLBACK_LISTINGS: Listing[] = [
  {
    id: 1,
    host_id: 1,
    title: "Luxury Glass Penthouse with City Views",
    description: "Located in the heart of South Delhi near Hauz Khas Village. Features floor-to-ceiling glass windows, private terrace garden, modern chef's kitchen, high-speed fiber WiFi, and 24/7 power backup.",
    category_id: "iconic_cities",
    property_type: "Entire penthouse",
    room_type: "Entire place",
    address: "Hauz Khas Enclave",
    city: "New Delhi",
    state: "Delhi NCR",
    country: "India",
    lat: 28.5494,
    lng: 77.2001,
    price_per_night: 7500.0,
    cleaning_fee: 1200.0,
    service_fee: 800.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.0,
    rating: 4.96,
    reviews_count: 54,
    amenities: ["wifi", "kitchen", "air_conditioning", "free_parking", "workspace", "tv", "elevator"],
    photos: [
      { id: 1, listing_id: 1, url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 },
      { id: 2, listing_id: 1, url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80", is_primary: false, display_order: 1 },
      { id: 3, listing_id: 1, url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80", is_primary: false, display_order: 2 }
    ],
    host: {
      id: 1,
      name: "Rajesh Sharma",
      email: "rajesh.sharma@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      bio: "Superhost running premier heritage stays and luxury penthouses across Delhi NCR & Goa.",
      is_host: true,
      is_superhost: true,
      joined_date: "2018"
    }
  },
  {
    id: 2,
    host_id: 1,
    title: "Modern Executive Suite near Expressway",
    description: "Ultra-modern luxury studio apartment in Noida Sector 62. Steps away from IT parks and metro station. Equipped with high-speed WiFi, smart TV, modular kitchen, and gym access.",
    category_id: "iconic_cities",
    property_type: "Entire apartment",
    room_type: "Entire place",
    address: "Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    lat: 28.6280,
    lng: 77.3649,
    price_per_night: 3500.0,
    cleaning_fee: 600.0,
    service_fee: 400.0,
    max_guests: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1.0,
    rating: 4.92,
    reviews_count: 38,
    amenities: ["wifi", "kitchen", "air_conditioning", "free_parking", "workspace", "gym", "tv"],
    photos: [
      { id: 4, listing_id: 2, url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 },
      { id: 5, listing_id: 2, url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80", is_primary: false, display_order: 1 }
    ],
    host: {
      id: 1,
      name: "Rajesh Sharma",
      email: "rajesh.sharma@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      bio: "Superhost running premier heritage stays and luxury penthouses across Delhi NCR & Goa.",
      is_host: true,
      is_superhost: true,
      joined_date: "2018"
    }
  },
  {
    id: 3,
    host_id: 1,
    title: "Cyber City Skylight Loft on Golf Course Road",
    description: "Premium duplex apartment situated in Gurugram's prime financial corridor. Features Italian marble flooring, plunge pool on private balcony, EV charger, and 24/7 security concierge.",
    category_id: "mansions",
    property_type: "Entire loft",
    room_type: "Entire place",
    address: "Golf Course Road, Sector 54",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    lat: 28.4393,
    lng: 77.1006,
    price_per_night: 8900.0,
    cleaning_fee: 1500.0,
    service_fee: 900.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.5,
    rating: 4.98,
    reviews_count: 67,
    amenities: ["wifi", "pool", "kitchen", "air_conditioning", "free_parking", "workspace", "gym"],
    photos: [
      { id: 6, listing_id: 3, url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 },
      { id: 7, listing_id: 3, url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80", is_primary: false, display_order: 1 }
    ],
    host: {
      id: 1,
      name: "Rajesh Sharma",
      email: "rajesh.sharma@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      bio: "Superhost running premier heritage stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2018"
    }
  },
  {
    id: 4,
    host_id: 1,
    title: "Portuguese Style Beach Villa with Private Pool",
    description: "Nestled in North Goa near Vagator Beach, Villa Sunset features Portuguese architecture, private swimming pool, lush tropical garden, open-air pavilion, and dedicated chef service.",
    category_id: "beachfront",
    property_type: "Entire villa",
    room_type: "Entire place",
    address: "Ozran Beach Road, Vagator",
    city: "Goa",
    state: "Goa",
    country: "India",
    lat: 15.5991,
    lng: 73.7445,
    price_per_night: 18500.0,
    cleaning_fee: 2500.0,
    service_fee: 1800.0,
    max_guests: 8,
    bedrooms: 4,
    beds: 4,
    bathrooms: 4.0,
    rating: 4.99,
    reviews_count: 120,
    amenities: ["wifi", "pool", "kitchen", "air_conditioning", "free_parking", "patio"],
    photos: [
      { id: 8, listing_id: 4, url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 },
      { id: 9, listing_id: 4, url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80", is_primary: false, display_order: 1 }
    ],
    host: {
      id: 1,
      name: "Rajesh Sharma",
      email: "rajesh.sharma@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      bio: "Superhost running premier heritage stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2018"
    }
  },
  {
    id: 5,
    host_id: 2,
    title: "Bandra Sea Face Luxury Apartment",
    description: "Panoramas of the Arabian Sea from Bandra West, Mumbai's most vibrant coastal neighborhood. Steps away from Carter Road promenade, coffee shops, and nightlife.",
    category_id: "beachfront",
    property_type: "Entire apartment",
    room_type: "Entire place",
    address: "Carter Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: 19.0596,
    lng: 72.8295,
    price_per_night: 14500.0,
    cleaning_fee: 2000.0,
    service_fee: 1500.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.0,
    rating: 4.95,
    reviews_count: 84,
    amenities: ["wifi", "kitchen", "air_conditioning", "free_parking", "workspace", "tv"],
    photos: [
      { id: 10, listing_id: 5, url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 2,
      name: "Priya Patel",
      email: "priya.patel@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
      bio: "Hospitality designer passionate about authentic stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2019"
    }
  },
  {
    id: 6,
    host_id: 2,
    title: "Snow Peak Cedar Chalet with Fireplace",
    description: "Wooden A-frame cabin surrounded by pine tree forests in Old Manali. Features a stone fireplace, heated cedar jacuzzi, balcony overlooking snow-capped Himalayan peaks, and apple orchard paths.",
    category_id: "cabins",
    property_type: "Entire cabin",
    room_type: "Entire place",
    address: "Log Huts Area, Old Manali",
    city: "Manali",
    state: "Himachal Pradesh",
    country: "India",
    lat: 32.2492,
    lng: 77.1802,
    price_per_night: 9800.0,
    cleaning_fee: 1400.0,
    service_fee: 1000.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.0,
    rating: 4.97,
    reviews_count: 91,
    amenities: ["wifi", "kitchen", "fireplace", "hot_tub", "heating", "workspace", "free_parking"],
    photos: [
      { id: 11, listing_id: 6, url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 2,
      name: "Priya Patel",
      email: "priya.patel@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
      bio: "Hospitality designer passionate about authentic stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2019"
    }
  },
  {
    id: 7,
    host_id: 3,
    title: "Royal Haveli Suite in Pink City",
    description: "Authentic 200-year-old Rajasthani heritage palace suite with jharokha balconies, hand-painted frescoes, courtyard garden, and traditional Rajasthani thali dining experience.",
    category_id: "mansions",
    property_type: "Heritage haveli",
    room_type: "Entire place",
    address: "Johari Bazar, Old City",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    lat: 26.9196,
    lng: 75.8243,
    price_per_night: 11200.0,
    cleaning_fee: 1600.0,
    service_fee: 1200.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.0,
    rating: 4.96,
    reviews_count: 105,
    amenities: ["wifi", "kitchen", "air_conditioning", "patio", "free_parking"],
    photos: [
      { id: 12, listing_id: 7, url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 3,
      name: "Vikramaditya Singh",
      email: "vikram.singh@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
      bio: "Royal heritage estate host preserving Rajasthani architecture.",
      is_host: true,
      is_superhost: false,
      joined_date: "2020"
    }
  },
  {
    id: 8,
    host_id: 3,
    title: "Lake Pichola Waterfront Heritage Villa",
    description: "Perched directly on the waters of Lake Pichola in Udaipur with views of Lake Palace and Jagmandir. Includes private boat transfers and rooftop sunset dining.",
    category_id: "lakefront",
    property_type: "Entire villa",
    room_type: "Entire place",
    address: "Hanuman Ghat",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    lat: 24.5800,
    lng: 73.6800,
    price_per_night: 16900.0,
    cleaning_fee: 2200.0,
    service_fee: 1700.0,
    max_guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3.0,
    rating: 4.98,
    reviews_count: 78,
    amenities: ["wifi", "pool", "kitchen", "air_conditioning", "patio"],
    photos: [
      { id: 13, listing_id: 8, url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 3,
      name: "Vikramaditya Singh",
      email: "vikram.singh@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
      bio: "Royal heritage estate host preserving Rajasthani architecture.",
      is_host: true,
      is_superhost: false,
      joined_date: "2020"
    }
  },
  {
    id: 9,
    host_id: 2,
    title: "Ganges Riverfront Eco Sanctuary",
    description: "Peaceful riverside eco-resort in Tapovan, Rishikesh with direct Ganges river access, yoga shala, organic cafe, and panoramic views of the Himalayan foothills.",
    category_id: "countryside",
    property_type: "Cottage",
    room_type: "Entire place",
    address: "Badrinath Road, Tapovan",
    city: "Rishikesh",
    state: "Uttarakhand",
    country: "India",
    lat: 30.1264,
    lng: 78.3242,
    price_per_night: 4800.0,
    cleaning_fee: 800.0,
    service_fee: 500.0,
    max_guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1.0,
    rating: 4.94,
    reviews_count: 64,
    amenities: ["wifi", "kitchen", "workspace", "patio", "free_parking"],
    photos: [
      { id: 14, listing_id: 9, url: "https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 2,
      name: "Priya Patel",
      email: "priya.patel@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
      bio: "Hospitality designer passionate about authentic stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2019"
    }
  },
  {
    id: 10,
    host_id: 2,
    title: "Munnar Tea Estate Heritage Bungalow",
    description: "Colonial-era planter's bungalow nestled amidst misty green tea gardens of Munnar, Kerala. Features wood-paneled fireplaces, plantation walks, and fresh estate tea.",
    category_id: "tropical",
    property_type: "Entire bungalow",
    room_type: "Entire place",
    address: "Tea Estate Road",
    city: "Munnar",
    state: "Kerala",
    country: "India",
    lat: 10.0889,
    lng: 77.0595,
    price_per_night: 8500.0,
    cleaning_fee: 1200.0,
    service_fee: 900.0,
    max_guests: 5,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2.5,
    rating: 4.96,
    reviews_count: 52,
    amenities: ["wifi", "kitchen", "fireplace", "patio", "free_parking"],
    photos: [
      { id: 15, listing_id: 10, url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 2,
      name: "Priya Patel",
      email: "priya.patel@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
      bio: "Hospitality designer passionate about authentic stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2019"
    }
  },
  {
    id: 11,
    host_id: 1,
    title: "Indiranagar Modernist Garden Duplex",
    description: "Architect-designed penthouse duplex in Indiranagar, Bengaluru. Surrounded by top cafes and tech hubs. Features private garden balcony, high-speed fiber WiFi, and smart home automation.",
    category_id: "iconic_cities",
    property_type: "Entire apartment",
    room_type: "Entire place",
    address: "100 Feet Road, Indiranagar",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    lat: 12.9784,
    lng: 77.6408,
    price_per_night: 6900.0,
    cleaning_fee: 1000.0,
    service_fee: 700.0,
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2.0,
    rating: 4.93,
    reviews_count: 71,
    amenities: ["wifi", "kitchen", "air_conditioning", "workspace", "gym", "free_parking", "tv"],
    photos: [
      { id: 16, listing_id: 11, url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 1,
      name: "Rajesh Sharma",
      email: "rajesh.sharma@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      bio: "Superhost running premier heritage stays.",
      is_host: true,
      is_superhost: true,
      joined_date: "2018"
    }
  },
  {
    id: 12,
    host_id: 3,
    title: "Taj Mahal View Luxury Villa",
    description: "Boutique villa located 1.5 km from the Taj Mahal in Agra. Offers direct rooftop Taj Mahal sunset view, marble courtyard, and private chef preparing Mughlai delicacies.",
    category_id: "mansions",
    property_type: "Entire villa",
    room_type: "Entire place",
    address: "Taj East Gate Road",
    city: "Agra",
    state: "Uttar Pradesh",
    country: "India",
    lat: 27.1739,
    lng: 78.0421,
    price_per_night: 12500.0,
    cleaning_fee: 1800.0,
    service_fee: 1300.0,
    max_guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3.0,
    rating: 4.97,
    reviews_count: 89,
    amenities: ["wifi", "pool", "kitchen", "air_conditioning", "free_parking"],
    photos: [
      { id: 17, listing_id: 12, url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80", is_primary: true, display_order: 0 }
    ],
    host: {
      id: 3,
      name: "Vikramaditya Singh",
      email: "vikram.singh@airbnb.com",
      avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
      bio: "Royal heritage estate host preserving Rajasthani architecture.",
      is_host: true,
      is_superhost: false,
      joined_date: "2020"
    }
  }
];
